stages:
   - deploy

# production stage
production:
   stage: deploy
   only:
      - master
   script:
      - cd "/home/taco/klunk-server/"
      - git pull https://taco:$TOKEN@code.fredag.nu/dricka/klunk-server.git
      - npm install